name: CI Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Grant Execute Permission for Gradle Wrapper
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
    - name: Build Plugin JAR
      run: ./gradlew buildPlugin
    - name: Process Plugin Zip
      run: |
        cd build/distributions
        # Get the name of the outer zip file
        DIST_ZIP=$(ls *.zip)
        # Extract just the plugin zip file without creating a directory
        unzip -j "$DIST_ZIP"
        # Remove the original distribution zip
        rm "$DIST_ZIP"
    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v4
      with:
        name: multi-file-copy
        path: build/distributions/*.zip
        compression-level: 0
