# .github/workflows/build.yml

name: CI Build and Test

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest  # The type of runner to use

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'    # JDK distribution; Temurin is recommended
        java-version: '17'         # Specify the Java version required for your plugin
        cache: 'gradle'            # Enable caching for Gradle dependencies

    # Step 3: Grant execute permission for Gradle Wrapper
    - name: Grant Execute Permission for Gradle Wrapper
      run: chmod +x gradlew

    # Step 4: Build the Project
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Run Tests
    - name: Run Tests
      run: ./gradlew test

    # Optional: Build the Plugin JAR
    - name: Build Plugin JAR
      run: ./gradlew buildPlugin

    # Optional: Upload Build Artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build/libs/
          build/distributions/
