name: CI Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Grant Execute Permission for Gradle Wrapper
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
    - name: Build Plugin JAR
      run: ./gradlew buildPlugin
    - name: Process Plugin Zip
      run: |
        cd build/distributions
        # Create publish directory
        mkdir publish
        # Get the name of the outer zip file
        DIST_ZIP=$(ls *.zip)
        # Extract into publish directory
        unzip "$DIST_ZIP" -d publish
    - name: Get Version
      id: get_version
      run: |
        VERSION=$(grep 'version =' build.gradle.kts | awk -F'"' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v4
      with:
        name: multi-file-copy-${{ steps.get_version.outputs.version }}-${{ github.run_id }
        path: build/distributions/publish/*
        compression-level: 0

