name: Release Plugin
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x gradlew
        
      - name: Build Plugin
        run: ./gradlew clean buildPlugin
        
      - name: Get Plugin Zip Name
        run: |
          cd build/distributions
          echo "DIST_ZIP=$(ls *.zip)" >> $GITHUB_ENV
        
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./build/distributions/${{ env.DIST_ZIP }}
          asset_name: ${{ env.DIST_ZIP }}
          asset_content_type: application/zip 